### ISSUE TITLE
Check status of an order?

### ISSUE THREAD

**Issue by daraosn** [0xProject/0x.js#122]
I'm trying to check the status of an order programmatically.

I have an order hash, how do I check if it's still available or if it was filler or cancelled? The docs are not quite clear to me, I spent one hour trying to figure it out...

This is what I have at the moment, but I have no idea how to do this... (using parity as provider)

```
const ZeroEx = require('0x.js').ZeroEx;
const web3 = require('web3');

let provider = new web3.providers.HttpProvider('http://localhost:8545/');
let parity = new web3(provider);

let orderHash = '0123456789abcdef...';

let zeroEx = new ZeroEx(provider);
zeroEx.???(orderHash) // <----- here, which method to use??
.then(function(res) {
    console.log(res);
})
.catch(function(error) {
    console.log('Caught error: ', error);
});
```

or should I subscribe to all changes in the orders using `subscribeAsync`?

**Comment by abandeali1** [comment]
Check out https://0xproject.com/docs/0xjs#getUnavailableTakerAmountAsync

Use `getFilledTakerTokenAmountAsync`,  `getCanceledTakerTokenAmountAsync`, or `getUnavailableTakerAmountAsync` depending on your needs.

**Comment by daraosn** [comment]
Thank you, I'm closing this now

**Comment by daraosn** [comment]
@abandeali1 
I'm sorry to reopen, but I haven't managed to use any of those methods to check a third party transaction, I keep getting the error:
```
Caught error:  Error: CONTRACT_DOES_NOT_EXIST
    at ExchangeWrapper.<anonymous> (./node_modules/0x.js/lib/src/contract_wrappers/contract_wrapper.js:94:35)
    at step (./node_modules/0x.js/lib/src/contract_wrappers/contract_wrapper.js:32:23)
    at Object.throw (./node_modules/0x.js/lib/src/contract_wrappers/contract_wrapper.js:13:53)
    at rejected (./node_modules/0x.js/lib/src/contract_wrappers/contract_wrapper.js:5:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

Same happens with other methods, what am I doing wrong?

**Comment by abandeali1** [comment]
Are you on mainnet or Kovan? Mainnet isn't up yet, but PR #118 should be merged soon.

**Comment by daraosn** [comment]
@abandeali1 I'm on mainnet. Could you clarify: is the OTC dApp running on Kovan?
Thanks again for the help.

**Comment by abandeali1** [comment]
OTC is on mainnet (and Kovan), but hasn't fully transitioned to 0x.js yet.

**Comment by fabioberger** [comment]
@daraosn, we just released 0x.js V0.9.2 with the updated artifacts with the latest Kovan and Mainnet deploys: https://www.npmjs.com/package/0x.js
