### ISSUE TITLE
getProxyAllowanceAsync() returning incorrect WETH allowance on Kovan

### ISSUE THREAD

**Issue by riteable** [0xProject/0x.js#164]
Network: Kovan
Web3 provider: MetaMask
Token address (WETH): 0x05d090b51c40b020eab3bfcb6a2dff130df22e9c
Owner address: 0xd5a5643589a2f017eb9545aed4c8c6d19930a008

Returned value: 115792089237316195423570985008687907853269984665640564039457584007913129639935

When I check the allowance on kovan.etherscan.io, it's 0. For a little context, I did test the Radar Relay app a couple of days ago, and used their wrap/unwrap function for WETH/ETH. I first wrapped some ETH and then unwrapped all of it.

**Comment by LogvinovLeon** [comment]
I've just checked Etherscan and allowance is set exactly to the returned amount.
<img width="693" alt="screen shot 2017-09-15 at 11 50 48" src="https://user-images.githubusercontent.com/6204356/30477028-2705871c-9a0c-11e7-89c6-e0aed7cc5aef.png">

**Comment by riteable** [comment]
Hmm, is the spenders address supposed to be the 0x contract address, which is returned by getContractAddressAsync()?

Because that's the address I tried, but I got a different one: 0x90fe2af704b34e0224bf2299c838e04d4dcf1364

**Comment by riteable** [comment]
Never mind. I used exchange.getContractAddressAsync() instead of proxy.getContractAddressAsync().

I think the docs are buggy, because when I click on getContractAddressAsync in the main menu, it goes to exchange.getContractAddressAsync instead of the correct one in the Proxy section.
