### ISSUE TITLE
Using entire WETH Balance in order returns INSUFFICIENT_MAKER_BALANCE 

### ISSUE THREAD

**Issue by apackin** [0xProject/0x.js#166]
Working on the Kovan Network:
Use Kovan address for WETH contract as makerTokenAddress: "0x05d090b51c40b020eab3bfcb6a2dff130df22e9c"
Set makerAmount to the balance from zeroEx.token.getBalanceAsync(makerTokenAddress, makerAddress)
Complete an otherwise valid order.
Sign order (not sure if this is required)
Submitting to zeroEx().exchange.validateFillOrderThrowIfInvalidAsync throws  INSUFFICIENT_MAKER_BALANCE

Changing the balance to -1 wei passes the validation. I figure this is a missing 'or equals' on a greater/less than. I'll see if I can find it. Seems to work fine when submitting total balance of ZRX token.

**Comment by LogvinovLeon** [comment]
Could you please paste an order (without signature)?
I just checked and we use `greaterThan` for all `balance/allowance` validations, which is correct.
This might be the problem with rounding during `fillMakerAmount` computation.
Will be nice to see `takerAmount`, `makerAmount` and `fillTakerAmount`.

**Comment by apackin** [comment]
Here is a similar example:

Taker will be account: 0xEb71bad396acAa128aEadBC7dBD59ca32263DE01
Current ZRX balance: 7721349919979265 

Trying to perform this batch fill:
```
[{
  "signedOrder": {
    "ecSignature": {
      "r": "0x878329a293bb14a42019d2f0583f0f6003e49cbf1ab738848bd37c5537b96a25",
      "s": "0x1b21ac49607606881c4f08c8f994410529fa9ad2b2252ec73ff561aff223d19f",
      "v": 27
    },
    "exchangeContractAddress": "0x90fe2af704b34e0224bf2299c838e04d4dcf1364",
    "expirationUnixTimestampSec": "1514452757",
    "feeRecipient": "0xeb71bad396acaa128aeadbc7dbd59ca32263de01",
    "maker": "0x825cf4ab733265702f9582cd4d10f457baeee38e",
    "makerFee": "0",
    "makerTokenAddress": "0x05d090b51c40b020eab3bfcb6a2dff130df22e9c",
    "makerTokenAmount": "989999999999999900",
    "salt": "87276384580698629138334991609897348028108012915977568200418381927530806470590",
    "taker": "0x0000000000000000000000000000000000000000",
    "takerFee": "1783783783783783",
    "takerTokenAddress": "0x6ff6c0ff1d68b964901f986d4c9fa3ac68346570",
    "takerTokenAmount": "891891891891891791"
  },
  "takerTokenFillAmount": "7698255154515718"
}]
```

Receiving: 
```
Error: INSUFFICIENT_TAKER_BALANCE
    at OrderValidationUtils.<anonymous> (order_validation_utils.js:215)
    at step (order_validation_utils.js:32)
    at Object.next (order_validation_utils.js:13)
    at fulfilled (order_validation_utils.js:4)
    at <anonymous>
```


I'm not sure if the fee is checked before or after balance, but I'm expecting that to be:
`takerTokenFillAmount.dividedBy(signedOrder.takerTokenAmount).mul(signedOrder.takerFee).round(0)` => 15396510309031

So the total order should be 15396510309031 + 7698255154515718 = 7713651664824749

**Comment by avonian** [comment]
having the exact same issue here, sample code https://gist.githubusercontent.com/avonian/834cbb25f60299036261b4b3fefa3857/raw/5962518ee5632e753f739cbaed6b38754d8d3959/INSUFFICIENT_MAKER_BALANCE

**Comment by LogvinovLeon** [comment]
I think - this release should fix it https://github.com/0xProject/0x.js/releases/tag/v0.22.2
