### ISSUE TITLE
Fix order validation when maker/takerToken is ZRX

### ISSUE THREAD

**Issue by abandeali1** [0xProject/0x.js#167]
When validating maker/taker balances and allowances for an order, we currently define the required amounts like so:

`const requiredTakerAmount = isTakerTokenZRX ? fillTakerAmount.plus(signedOrder.takerFee) : fillTakerAmount;`

However, this does not account for intermediate state changes. A trader should be able to trade for ZRX and then use that ZRX to pay the fees for that fill. Therefore, as long as the required fee is less than the amount of ZRX that the trader will receive, the trader's ZRX balance should be considered valid (note that they still need a ZRX allowance in order to pay fees).

**Comment by fabioberger** [comment]
Fixed in #181
