### ISSUE TITLE
zeroEx.etherToken.withdrawAsync fails with Error: Invalid number of arguments to Solidity function

### ISSUE THREAD

**Issue by atygr** [0xProject/0x.js#176]
Probably the filter at SolidityFunction.prototype.validateArgs is wrong.

**Comment by LogvinovLeon** [comment]
This is probably the BigNumber problem. The way web3 checks if the last arg is txOpts is checking that it's an object but not a BigNumber. And the way it checks for a BigNumber is by checking the constructor name, which is sometimes mangled by minifiers. Can you tell more about your env? Which web3/BigNumber do you use? Do you minify stuff?

**Comment by atygr** [comment]
Thanks for the quick answer! The error occurs only with minified version BigNumber. 
Method withdrawAsync(bn, address) has BigNumber argument at first position (not last), so validateArgs filter all arguments, not only last.

**Comment by LogvinovLeon** [comment]
You can still minify your code, but you'll need to prevent BigNumber name from being mangled.
Example: https://github.com/0xProject/website/blob/development/webpack.config.js#L82

**Comment by MarcZenn** [comment]
It seems that even when preventing BigNumber name from being mangled in webpack the issue still comes up when attempting to call `zeroEx.token.setUnlimitedProxyAllowanceAsync`, `zeroEx.token.setProxyAllowanceAsync` and
`zeroEx.etherToken.withdrawAsync` on 0x.js version 0.22.6  given the following config:

```
new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: true,
        // Disabled because of an issue with Uglify breaking seemingly valid code:
        // https://github.com/facebookincubator/create-react-app/issues/2376
        // Pending further investigation:
        // https://github.com/mishoo/UglifyJS2/issues/2011
        comparisons: true
      },
      output: {
        comments: false,
        // Turned on because emoji and regex is not minified properly using default
        // https://github.com/facebookincubator/create-react-app/issues/2488
        ascii_only: true
      },
      sourceMap: shouldUseSourceMap,
      mangle: {
        except: ['BigNumber']
      }
    })
```

interestingly enough, `zeroEx.etherToken.depositAsync` works fine without mangle prevention.

**Comment by fabioberger** [comment]
Example webpack.config: https://github.com/0xProject/0x.js/blob/development/packages/website/webpack.config.js#L80
