### ISSUE TITLE
OrderFillOrKillRequest and OrderFillRequest use different interface

### ISSUE THREAD

**Issue by apackin** [0xProject/0x.js#186]
Is there are a reason these interfaces need to be different? I think it would make more sense if we stick to either `fillTakerAmount` or `takerTokenFillAmount` for both of these interfaces

```
Interface OrderFillOrKillRequest
{
	fillTakerAmount: BigNumber,
	signedOrder: SignedOrder,
}
Interface OrderFillRequest
{
	signedOrder: SignedOrder,
	takerTokenFillAmount: BigNumber,
}
```

**Comment by fabioberger** [comment]
Yup, that's an oversight. Let's standardize around `takerTokenFillAmount`.
