### ISSUE TITLE
INSUFFICIENT_TAKER_ALLOWANCE error using fillOrdersUpToAsync() on Kovan

### ISSUE THREAD

**Issue by riteable** [0xProject/0x.js#192]
Using `0.21.2`

When I visit the [0x portal](https://0xproject.com/portal/balances), I can see that all my tokens have Trade Permissions enabled. Also, token.getProxyAllowanceAsync() confirms that my allowance is "unlimited" for both the maker and taker tokens.

But calling `fillOrdersUpToAsync()` gives me the `INSUFFICIENT_TAKER_ALLOWANCE` error. I didn't have this problem using v0.20.0, but I can't test right now.

I can see that there's an issue closed regarding this: https://github.com/0xProject/0x.js/issues/191

But it doesn't seem like it's been actually resolved.

**Comment by riteable** [comment]
Example inputs:

Orders: 
```
[{
    exchangeContractAddress: "0x90fe2af704b34e0224bf2299c838e04d4dcf1364"
    expirationUnixTimestampSec: "1507889685"
    feeRecipient: "0x55a15abe0ce6f300fb3611774f0fcabb9b8b7746"
    maker: "0xd5a5643589a2f017eb9545aed4c8c6d19930a008"
    makerFee: "1000000000000000"
    makerTokenAddress: "0x05d090b51c40b020eab3bfcb6a2dff130df22e9c"
    makerTokenAmount: "1000000000000000"
    salt: "85825171920840012471709344206933845282844847914146827640747330560410049403401"
    taker: "0x0000000000000000000000000000000000000000"
    takerFee: "2000000000000000"
    takerTokenAddress: "0x1dad4783cf3fe3085c1426157ab175a6119a04ba"
    takerTokenAmount: "1350000000000000"
}]
```

Amount: 1350000000000000

Taker address: 0x6c31964d56a67fedacba8628563167cd122d3120

**Comment by LogvinovLeon** [comment]
Could you please construct a smallest repro for this?
We have tests for this behaviour and they pass.
I'd like to help, but I can't reproduce it.
You can also just just debugging it yourself by placing some `console.log's` in `node_modules`.
Or linking this library to your project

**Comment by LogvinovLeon** [comment]
I'm able to reproduce. Will work on that. Thx for reporting

**Comment by LogvinovLeon** [comment]
I’ve found an issue and will release the fix in the next couple of hours.
