### ISSUE TITLE
Some bigNumber order amount can not pass the ZeroEx.getOrderHashHex validation

### ISSUE THREAD

**Issue by Xaber20110202** [0xProject/0x.js#238]
https://github.com/0xProject/0x.js/blob/4d61d56639ad70b13245ca25047c6f299e746393/packages/json-schemas/src/schema_validator.ts#L21

when order makerTokenAmount bignumber like this `makerTokenAmount = new BigNumber(1e21)`

it can not pass the validation, because that JSON.stringify will can `BigNumberInstance.toString()`, so it will get string 1e21, but not string 1000000000000000000000, unless we configure bigNumber

**Comment by LogvinovLeon** [comment]
Yes. The solution to that is to config your BigNumber.
https://github.com/0xProject/0x.js/blob/development/packages/0x.js/src/bignumber_config.ts#L7
We'll add it to the docs.

**Comment by Xaber20110202** [comment]
Thanks
