### ISSUE TITLE
With 0x.js v0.27.1 Webpack fails to minify `./node_modules/ethereum-address/index.js:3` when running a build

### ISSUE THREAD

**Issue by MarcZenn** [0xProject/0x.js#254]
Here's an output of the command failure error: 

```
yarn build v0.27.5
$ node_modules/.bin/tsc -p ./ && node scripts/build.js
Creating an optimized production build...
ts-loader: Using typescript@2.5.3 and /Users/marczenn/Desktop/par-ui/tsconfig.json
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/ethereum-address/index.js:3

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
```

**Comment by MarcZenn** [comment]
I believe I found a way around this. Please see https://github.com/ccxt/ccxt/issues/299. 

It seems that because there isn't a transpiled version of `./node_modules/ethereum-address/index.js:3` You can use the following hack to circumvent the issue. 

```
      {
        test: require.resolve("ethereum-address"),
        loader: require.resolve("babel-loader"),
        options: { compact: true }
      },
```

This definitely is NOT the way to solve the problem but for now it can get you by.

**Comment by fabioberger** [comment]
Yep, we can remove this dependency and re-implement it ourselves.

**Comment by davidqhr** [comment]
Please remove this dependency.

Now, I have to compile this file in the ci process.
```
node_modules/.bin/babel node_modules/ethereum-address/index.js > node_modules/ethereum-address/index.js
```

**Comment by davidqhr** [comment]
@LogvinovLeon 

I found ethereum-address is still a dependency of @0xproject/assert

[https://github.com/0xProject/0x.js/blob/a6f97181310c9acba176b2a28ffba1ca7d53727d/packages/assert/package.json#L42](https://github.com/0xProject/0x.js/blob/a6f97181310c9acba176b2a28ffba1ca7d53727d/packages/assert/package.json#L42)
