### ISSUE TITLE
Documentation links reference first instance of methods with the same name

### ISSUE THREAD

**Issue by abandeali1** [0xProject/0x.js#281]
If a method of the same name preciously exists within the documentation, the links go to the first instance of that method rather than the correct one. For example, `orderwatcher.subscribe` links to `exchange.subscribe` (urls for both are: https://0xproject.com/docs/0xjs#subscribe).

**Comment by fabioberger** [comment]
Fixed: https://github.com/0xProject/0x.js/pull/288
