### ISSUE TITLE
numberSchema does not handle exponential numbers

### ISSUE THREAD

**Issue by felix2feng** [0xProject/0x.js#293]
I came upon this issue when I sent a 0x order via REST to a node.js server. The salt that is generated using "generatePseudoRandomSalt" is a large number stringified (e.g. "40599983934626278298511948302963119827536450249312932036852600602882883328979"). When calling new BigNumber() on this string, it results in an exponential number - which fails the the schema validator. Should we add the ability to handle exponential figures in this validation?

File: `0x.js/packages/json-schemas/schemas/basic_type_schemas.ts`
```
export const numberSchema = {
    id: '/Number',
    type: 'string',
    pattern: '^\\d+(\\.\\d+)?$',
};
````

**Comment by felix2feng** [comment]
If we're configuring our BigNumber into exponentials, this isn't too much of an issue. But it would be nice to support exponentials out of the box.

**Comment by fabioberger** [comment]
I think this is something worth discussing. The counter-argument to supporting exponentials is that doing so requires the receiving end to handle both the case where the amount is in exponential notation and an integer value. There is simplicity in knowing that one only needs to handle the integer case.

**Comment by fabioberger** [comment]
The espoused solution is to configure bigNumber to not use exponential notation:

```
BigNumber.config({
    EXPONENTIAL_AT: 1000,
});
```
