### ISSUE TITLE
Unable to catch rejection

### ISSUE THREAD

**Issue by steveklebanoff** [0xProject/0x.js#308]
I may be missing something, but I've having trouble with catching promise rejections using 0x. 

I've tried:

```js
async function check() {
  try {
    const r = await zeroEx.awaitTransactionMinedAsync('0xfake');
  } catch(e) {
    console.log('caught');
  }
}
```

I've also tried chaining `.catch` to the promise itself.

Either way, I don't see my catch statement executing, and I see:

```
(node:17129) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: invalid argument 0: hex string has length 4, want 64 for common.Hash
(node:17129) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Am I doing something wrong? Or could there be an issue with the library?

**Comment by LogvinovLeon** [comment]
Thanks for reporting that. Fixing it caused us to think deeper about error handling in repeated processes and caused some interface changes and internal changes that will prevent those type of bugs in future
