### ISSUE TITLE
Is the `exchange contract address` correct on testrpc?

### ISSUE THREAD

**Issue by davidqhr** [0xProject/0x.js#331]
exchange contract address on testrpc
[https://github.com/0xProject/0x.js/blob/a767c353d25588cf5802868ee7b3710e99316e96/packages/0x.js/src/artifacts/Exchange.json#L603-L605](https://github.com/0xProject/0x.js/blob/a767c353d25588cf5802868ee7b3710e99316e96/packages/0x.js/src/artifacts/Exchange.json#L603-L605)

testrpc readyme 
![image](https://user-images.githubusercontent.com/5846959/35211985-90a94edc-ff93-11e7-8978-7b03df1d7866.png)

so the exchange contract address was set as same as EtherToken address?

**Comment by abandeali1** [comment]
The artifact addresses are correct. I have updated the wiki to reflect that.
