### ISSUE TITLE
Geth: signOrderHashAsync throws ZeroExError.InvalidSignature

### ISSUE THREAD

**Issue by kabl** [0xProject/0x.js#340]
Using Geth: 1.7.3-stable-4bb3c89d

`
signOrderHashAsync(orderHash: string, signerAddress: string) //always throws: new Error(ZeroExError.InvalidSignature)
`

This code snipped produces a valid signature:

`
const signature = web3.eth.sign(makerAddress, orderHash);
`
`
const ecSignature = <ECSignature>signatureUtils.parseSignatureHexAsRSV(signature);
`

**Comment by abandeali1** [comment]
I think the issue lies here: https://github.com/0xProject/0x.js/blob/development/packages/0x.js/src/0x.ts#L254

Pretty sure Geth also automatically adds the personalMessage prefix, in which case we are unnecessarily adding it.

**Comment by BMillman19** [comment]
Should be fixed with https://github.com/0xProject/0x.js/pull/349
