### ISSUE TITLE
 No more getContractAddress on EtherTokenWrapper

### ISSUE THREAD

**Issue by justinkchen** [0xProject/0x.js#345]
How do we call the methods on the EtherTokenWrapper now that there is no way to get the WETH contract address via `getContractAddress`? Are we supposed to hard-code the address somewhere?

**Comment by justinkchen** [comment]
The wiki should be updated to reflect this btw (also the fact that `config` is required for the `ZeroEx` constructor in newer versions)

**Comment by fabioberger** [comment]
Hi Justin, in what context are you trying to get the EtherToken address?

Re: wiki, what part of the wiki is currently out of date?

**Comment by justinkchen** [comment]
Hi @fabioberger , the wiki (https://0xproject.com/wiki) shows to get the WETH_ADDRESS via this call: `const WETH_ADDRESS = await zeroEx.etherToken.getContractAddressAsync();`, and the EXCHANGE_ADDRESS via: `const EXCHANGE_ADDRESS = await zeroEx.exchange.getContractAddressAsync();`.

Looking through the latest version (0.30.1) of 0x.js, the EXCHANGE_ADDRESS has changed to `zeroEx.exchange.getContractAddress()`, but the `etherToken` method has been removed.

Also, the wiki says to instantiate ZeroEx like this:
```
// Instantiate 0x.js instance
const zeroEx = new ZeroEx(provider);
```
but the ZeroEx constructor has a required `config` parameter in latest versions too now

**Comment by justinkchen** [comment]
P.S. I know that the docs are up to date here: https://0xproject.com/docs/0xjs, but just saying that the wiki is no longer compatible with the docs

**Comment by fabioberger** [comment]
Thanks for the heads up @justinkchen! Going to update the wiki today!

**Comment by justinkchen** [comment]
thanks! :)

**Comment by justinkchen** [comment]
@fabioberger whenever I try to do any kind of methods on the ethertoken contract, I keep getting `InvalidNumberOfSolidityArgs` as an error. Is there something wrong with the smart contract that is deployed?

**Comment by justinkchen** [comment]
The error happens when I try to run ```zeroEx.token.setAllowanceAsync(
      tokenContractAddress,
      account,
      zeroExProxyContractAddress,
      new BigNumber(0),
    );```

where i get the token address from here: https://0xproject.com/wiki#Deployed-Addresses (on Ropsten)

**Comment by justinkchen** [comment]
I think the issue is coming from the BigNumber not being treated as a single variable but instead being an array.  Any ideas as to why? Is it a poor installation or something?

**Comment by justinkchen** [comment]
<img width="482" alt="screen shot 2018-01-30 at 2 05 47 am" src="https://user-images.githubusercontent.com/1000741/35560453-519280d6-0562-11e8-91e3-edaa93a14453.png">
as you can see in my dev console, the argument that is supposed to be the `amountInBaseUnits` is being passed as an object instead of a BigNumber

**Comment by justinkchen** [comment]
here is the actual method call ``` await zeroEx.token.setAllowanceAsync(
      tokenContractAddress,
      account,
      zeroExProxyContractAddress,
      new BigNumber(0),
    );``` and this is on 0.30.1 version of 0x.js

**Comment by justinkchen** [comment]
I found the issue. It happens when trying to use the method while statically serving the files (whether through `serve -s build` or `express.static`) still can't find the solution though...

**Comment by fabioberger** [comment]
@justinkchen can you try with BigNumber.js version ~4.1.0? Also, let's continue this conversation at chat.0xproject.com #dev channel.
