### ISSUE TITLE
Unable to set gas price with zeroEx.exchange.fillOrderAsync

### ISSUE THREAD

**Issue by rreichman** [0xProject/0x.js#347]
It's supposed to be possible to add a custom gas price to this request but I don't see it anywhere in the documentation. Where can I find it?

Thanks in advance,
Ran

**Comment by BMillman19** [comment]
@rreichman https://0xproject.com/docs/0xjs#exchange-fillOrderAsync `orderTransactionOpts`

**Comment by BMillman19** [comment]
@rreichman let me know if this satisfies your needs, we can reopen this issue otherwise

**Comment by rreichman** [comment]
Yep, missed that. Thanks!
