### ISSUE TITLE
Error on import @0xproject/subproviders 

### ISSUE THREAD

**Issue by Ellieutt** [0xProject/0x.js#348]
Hi, I wanted to try your @0xproject/subproviders package in an angular dapp.
I followed the usage instructions in the readme
But when trying to do the import :
```
import {
    ledgerEthereumBrowserClientFactoryAsync as ledgerEthereumClientFactoryAsync,
    LedgerSubprovider,
} from '@0xproject/subproviders';
```

 I get the following error:
```
ERROR in node_modules/@0xproject/subproviders/lib/src/subproviders/injected_web3.d.ts(6,28): error TS2503: Cannot find namespace 'Web3'.
node_modules/@0xproject/subproviders/lib/src/subproviders/ledger.d.ts(18,28): error TS2503: Cannot find namespace 'Web3'.
```

**Comment by BMillman19** [comment]
@Ellieutt try including the `web3-typescript-typings` package in your project and adding a corresponding entry to the `include` property in your project's `tsconfig.json` See https://github.com/0xProject/0x.js/blob/development/packages/connect/tsconfig.json as an example

**Comment by Ellieutt** [comment]
Thank you for your help @BMillman19 , it did work adding `web3-typescript-typings` and including it in my `tsconfig.json`.
I also had to install '@0xproject/types' in my project.

I noticed there is an error in doc, you have to put the parameters as a json object in brackets when calling `new LedgerSubprovider`.
Like that : 
```
ledgerSubprovider = new LedgerSubprovider({
            networkId: networkId,
            ledgerEthereumClientFactoryAsync: ledgerEthereumClientFactoryAsync,
        });
```

**Comment by dekz** [comment]
thanks @Ellieutt, we've updated the README to fix that typo.

Going to close this issue as it seems to be resolved.
