### ISSUE TITLE
BigNumber v6 breaks 0x asserts

### ISSUE THREAD

**Issue by avonian** [0xProject/0x.js#403]
Just thought I'd point out that BigNumber 6.0 breaks the assert for `isBigNumber`, it's not a big deal but thought to put it on your radar.

**Comment by BMillman19** [comment]
@avonian Looking into a larger upgrade to BigNumber v6 instead. We actually export `BigNumber` from our `@0xproject/utils` package, this allows us to consistently configure `BigNumber` across multiple packages and stay in sync with respect to version. If you want to use that version of BigNumber it will almost always be more compatible with `@0xproject` packages

**Comment by avonian** [comment]
Ah! duly noted, will rely on that instead moving forward, thanks!
